FROM centos:7

USER root
RUN yum -y install openssh-server && yum -y install  openssh-client 

RUN useradd ansible && \
    echo "1234" | passwd ansible  --stdin 

RUN ssh-keygen -A

USER ansible

WORKDIR /home/ansible

CMD ["/usr/sbin/init"]