FROM centos:7

RUN yum update -y && yum upgrade -y
RUN yum -y install openssh-server && yum -y install  openssh-clients
RUN yum install -y \
    epel-release \
    python3 \
    sudo
RUN yum install ansible -y
RUN useradd ansible && \
    echo "1234" | passwd ansible  --stdin 


RUN ssh-keygen -A
WORKDIR /home/ansible

CMD ["/usr/sbin/init"]