FROM centos:7

RUN yum -y install openssh-server
RUN yum update -y && yum upgrade -y && yum -y install \
    epel-release \
    python3 \
    sudo \
    vim
    
RUN useradd centos1 && \
    echo "1234" | passwd centos1  --stdin 

RUN ssh-keygen -A

WORKDIR /home/centos1

CMD ["/usr/sbin/init"]