version: '3.9'
services: 
  ansible:
    container_name: ansible
    image: ansible:v1
    hostname: ansible
    build:
      context: ansible
    ports: 
      - "8081:80"
    volumes: 
      - $PWD/ansible/data:/home/ansible
    privileged: true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2000M
    networks: 
      default:
        ipv4_address: 10.130.2.130

  centos1:
    container_name: centos1
    image: centos1
    hostname: centos1
    build:
      context: centos1
    volumes: 
      - $PWD/centos1/data:/home/centos1
    privileged: true
    ports: 
      - "8083:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2000M
    networks: 
      default:
        ipv4_address: 10.130.2.31

  centos2:
    container_name: centos2
    image: centos2
    hostname: centos2
    build:
      context: centos2
    volumes: 
      - $PWD/centos2/data:/home/centos2
    privileged: true
    ports: 
      - "8082:80"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2000M
    networks: 
      default:
        ipv4_address: 10.130.2.200

  ubuntu3:
    container_name: ubuntu3
    image: ubuntu3
    hostname: ubuntu3
    build:
      context: ubuntu3
    volumes: 
      - $PWD/ubuntu3/data:/home/ubuntu
    privileged: true
    ports: 
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2000M
    networks: 
      default:
        ipv4_address: 10.130.2.201
networks:
  default:
    external: true  
    name: red1