version: '3.9'
services: 
  centos1:
    container_name: centos1
    image: centos1
    hostname: pruebaHost
    build:
      context: centos1
    volumes: 
      - $PWD/centos1/data:/home/centos1
    privileged: true
    ports: 
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2000M
networks:
  default:
    external: true
    name: red1